### ISSUE TITLE
Test if an organization name can be longer than the column for it.

### ISSUE THREAD

**Issue by carlosms** [src-d/ghsync#50]
In #48 the status table contains a column org VARCHAR (50).
Is it possible that we'll have org names longer than 50?

**Comment by se7entyse7en** [comment]
I tried to create an org and rename it until reaching the limit:

<img width="493" alt="Screenshot 2019-06-28 at 16 51 08" src="https://user-images.githubusercontent.com/5599208/60350953-013ea300-99c5-11e9-9ca6-b275872017b2.png">

So, in theory, we could use the same value, but I don't think it's a big deal.

**Comment by carlosms** [comment]
If the max org name is lower than our column length, it's ok.
Thanks for checking.
