### ISSUE TITLE
ghsync fails when running `sourced init local`

### ISSUE THREAD

**Issue by dpordomingo** [src-d/ghsync#54]
https://github.com/src-d/gitcollector/issues/64

When **source{d} CE** is inited with a local workdir, `shsync` is started and then it fails fast because it was not passed an org.

```shell
$ export GHSYNC_POSTGRES_DB=metadata
$ export GHSYNC_POSTGRES_USER=metadata
$ export GHSYNC_POSTGRES_PASSWORD=metadata
$ export GHSYNC_POSTGRES_HOST=127.0.0.1
$ export GHSYNC_POSTGRES_PORT=5433
$ export GHSYNC_TOKEN=
$ export GHSYNC_ORGS=
$ ghsync shallow
INFO connection with the DB established
INFO status table 'status' created
GET https://api.github.com/orgs/: 401 Bad credentials []
```

It should have the same behavior than `gitcollector`, and imo it should be the following:
if an empty org is passed, it should exit `0` (as `gitcollector` does), and log a warning,
e.g. `no organizations to scrape`

**Comment by carlosms** [comment]
This is tricky, because what you describe is more convenient from the sourced-ce point of view. But from the point of view of ghsync, it's correct to fail when a mandatory argument is not given.

**Comment by smacker** [comment]
+1 for failing without argument

**Comment by dpordomingo** [comment]
There is no expected external use case for `ghsync`, and the proposed one https://github.com/src-d/ghsync/pull/56 follows the same approach as implemented in `gitcollector`.

On the other hand, forcing **source{d} CE** to handle this use case can be not that trivial, and it's also reasonable that if you ask `ghsync` to collect data from a list of orgs, and the list is empty, then it will return: ok, I collect data for the list that you passed me.
